import Head from 'next/head';
import SideBar from '../components/common/sidebar/SideBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="my-20 flex">
          <SideBar />
          <div className="container mx-10 mt-12">
            <div className="grid grid-cols-1 gap-6 mb-6 lg:grid-cols-3">
              <div className="w-full px-4 py-5 bg-white rounded-lg shadow">
                <div className="text-sm font-medium text-gray-500 truncate">
                  Total users
                </div>
                <div className="mt-1 text-3xl font-semibold text-gray-900">
                  12,00
                </div>
              </div>
              <div className="w-full px-4 py-5 bg-white rounded-lg shadow">
                <div className="text-sm font-medium text-gray-500 truncate">
                  Total Profit
                </div>
                <div className="mt-1 text-3xl font-semibold text-gray-900">
                  $ 450k
                </div>
              </div>
              <div className="w-full px-4 py-5 bg-white rounded-lg shadow">
                <div className="text-sm font-medium text-gray-500 truncate">
                  Total Orders
                </div>
                <div className="mt-1 text-3xl font-semibold text-gray-900">
                  20k
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
