import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="my-20">
          <h1 className="md:text-8xl text-4xl font-bold text-center text-gray-900">
            Responsive<span className="text-blue-700"> Footer</span> using{' '}
            <span className="text-blue-700">Nextjs</span> &{' '}
            <span className="text-blue-700">Tailwindcss</span>
          </h1>
        </div>
      </main>
    </>
  );
}
